### ISSUE TITLE
Congratulations Xin!! I notice you received AP offer in Vanderbilt University

### ISSUE THREAD

**Issue by Shicheng-Guo** [maiziex/MARS#1]
Congratulations Xin!! I notice you received AP offer in Vanderbilt University!!! Really amazing achievement.

**Comment by maiziex** [comment]
Hi Shicheng,
Thanks! I just started my job one week ago. 🙂
How are you doing recently?


Best,
Xin

________________________________

**Comment by Shicheng-Guo** [comment]
Dear Xin,

Let's have a talk. What's your wechat id? my id is Shicheng_Guo

Best,

Shicheng
